### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by VolshebnikZS** [leap0x7b/Droidcord#1]
Android 2.3.4
Log:

> I/ActivityManager(  159): Start proc leap.droidcord for activity leap.droidcord/.MainActivity: pid=24652 uid=10034 gids={3003}
> I/OrientationDebug(  159): [pwm] in updateOrientationListenerLp()
> V/OrientationDebug(  159): in updateOrientationListenerLp(), Screen status=true, current orientation=-1, SensorEnabled=false
> I/OrientationDebug(  159): [pwm] needSensorRunningLp(), return false #3
> I/Launcher(  226): onWindowFocusChanged(false)
> D/Launcher(  226): setWallpaperDimension() called
> D/Launcher(  226): USE_NON_SCROLLABLE_IMAGE_WALLPAPER is true
> D/Launcher(  226): It's image wallpaper. suggestDesiredDimensions(-1,-1)
> W/System.err(24652): Error: JSONException: Empty text
> W/InputManagerService(  159): Got RemoteException sending setActive(false) notification to pid 24613 uid 10034
> I/ActivityManager(  159): Displayed leap.droidcord/.MainActivity: +428ms
> D/SntpClient(  159): request time failed: java.net.SocketTimeoutException: Try again
> D/GpsLocationProvider(  159): requestTime failed
> W/ActivityManager(  159): Activity destroy timeout for HistoryRecord{408d7d60 leap.droidcord/.MainActivity}
> W/System.err(24652): Error: java.io.IOException: Received authentication challenge is null
> W/PowerManagerService(  159): Timer 0x3->0x3|0x1
> W/System.err(24652): java.io.IOException: Received authentication challenge is null
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.processAuthHeader(HttpURLConnectionImpl.java:1153)
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:1095)
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.retrieveResponse(HttpURLConnectionImpl.java:1048)
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:512)
> W/System.err(24652):    at leap.droidcord.HTTPThing.sendRequest(HTTPThing.java:80)
> W/System.err(24652):    at leap.droidcord.HTTPThing.get(HTTPThing.java:160)
> W/System.err(24652):    at leap.droidcord.HTTPThread.run(HTTPThread.java:92)
> W/System.err(24652):    at leap.droidcord.MainActivity$1.run(MainActivity.java:87)
> W/System.err(24652):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
> W/System.err(24652):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
> W/System.err(24652):    at java.lang.Thread.run(Thread.java:1019)
> D/BatteryService(  159): update start
> D/BatteryService(  159): update start
> D/BatteryService(  159): update start
> W/System.err(24652): Error: java.io.IOException: Received authentication challenge is null
> W/System.err(24652): java.io.IOException: Received authentication challenge is null
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.processAuthHeader(HttpURLConnectionImpl.java:1153)
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.processResponseHeaders(HttpURLConnectionImpl.java:1095)
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.retrieveResponse(HttpURLConnectionImpl.java:1048)
> W/System.err(24652):    at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:512)
> W/System.err(24652):    at leap.droidcord.HTTPThing.sendRequest(HTTPThing.java:80)
> W/System.err(24652):    at leap.droidcord.HTTPThing.get(HTTPThing.java:160)
> W/System.err(24652):    at leap.droidcord.HTTPThread.run(HTTPThread.java:141)
> W/System.err(24652):    at leap.droidcord.MainActivity$1.run(MainActivity.java:88)
> W/System.err(24652):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
> W/System.err(24652):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
> W/System.err(24652):    at java.lang.Thread.run(Thread.java:1019)
> D/AndroidRuntime(24652): Shutting down VM
> W/dalvikvm(24652): threadid=1: thread exiting with uncaught exception (group=0x40018578)
> E/AndroidRuntime(24652): FATAL EXCEPTION: main
> E/AndroidRuntime(24652): java.lang.NullPointerException
> E/AndroidRuntime(24652):        at leap.droidcord.GuildListAdapter.getGroupCount(GuildListAdapter.java:115)
> E/AndroidRuntime(24652):        at android.widget.ExpandableListConnector.getCount(ExpandableListConnector.java:396)
> E/AndroidRuntime(24652):        at android.widget.ListView.setAdapter(ListView.java:502)
> E/AndroidRuntime(24652):        at android.widget.ExpandableListView.setAdapter(ExpandableListView.java:505)
> E/AndroidRuntime(24652):        at leap.droidcord.MainActivity$1$1.run(MainActivity.java:96)
> E/AndroidRuntime(24652):        at android.os.Handler.handleCallback(Handler.java:587)
> E/AndroidRuntime(24652):        at android.os.Handler.dispatchMessage(Handler.java:92)
> E/AndroidRuntime(24652):        at android.os.Looper.loop(Looper.java:130)
> E/AndroidRuntime(24652):        at android.app.ActivityThread.main(ActivityThread.java:3687)
> E/AndroidRuntime(24652):        at java.lang.reflect.Method.invokeNative(Native Method)
> E/AndroidRuntime(24652):        at java.lang.reflect.Method.invoke(Method.java:507)
> E/AndroidRuntime(24652):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
> E/AndroidRuntime(24652):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
> E/AndroidRuntime(24652):        at dalvik.system.NativeStart.main(Native Method)
> W/ActivityManager(  159):   Force finishing activity leap.droidcord/.MainActivity

**Comment by gitmanbloggus** [comment]
same error, 2.3.7 on jetdroid
